---
- name: build nginx image
  docker_image: path="/vagrant/docker/nginx" name="homework/nginx" state=build

- name: build static-site image
  docker_image: path="/vagrant/docker/static-site" name="homework/static-site" state=build

- name: start web01
  docker:
    image: homework/static-site
    name: web01
    docker_url: unix:///var/run/weave.sock
    detach: false
    state: reloaded
 
- name: start web02
  docker:
    image: homework/static-site
    name: web02
    detach: false
    state: reloaded
    docker_url: unix:///var/run/weave.sock