---
- name: build haproxy config
  template: src=haproxy.cfg.j2 dest=/vagrant/docker/haproxy/haproxy.cfg

- name: build haproxy image
  docker_image: path="/vagrant/docker/haproxy" name="homework/haproxy" state=build

- name: start lb01
  docker:
    image: homework/haproxy
    name: lb01
    state: reloaded
    docker_url: unix:///var/run/weave.sock
    ports:
      - 80:80
      - 9000:9000